### ISSUE TITLE
Need assistance in using mailpit in our app

### ISSUE THREAD

**Issue by N6REJ** [axllent/mailpit#14]
Hello;
We're trying to move away from mailhog and instead use mailpit in our wamp stack but are running into an issue where the service doesn't start.  I suspect it has something to do with this line https://github.com/Bearsampp/Bearsampp/blob/99c82d0152bf766427dfc223b1f33918eb8c0846/core/classes/bins/class.bin.mailpit.php#L6
we're not php pro's so this is a bit of a daunting task for us.
We're the only 100% portable WAMP stack that I'm aware of so I'd really like to support this exposure of this project by adding mailpit to our software.
Perhaps someone here could lend some guidance?
Thanks in advance
Bear

p.s. here's our config for mailpit 
https://github.com/Bearsampp/module-mailpit/blob/main/bin/mailpit1.1.5/bearsampp.conf

**Comment by axllent** [comment]
Hi @N6REJ. I think you're quite right, the command line flags that are being passed through to Mailpit aren't compatible as they are specific to MailHog. It's worth nothing that Mailpit is not a drop-in replacement for MailHog but a replacement for it. Please note that I do not know what your requirements for your WAMP stack are, however I suspect just a listening SMTP port and email capture/viewing via a web UI? If so then you're on the right track.

`-hostname localhost -api-bind-addr 127.0.0.1:%d -ui-bind-addr 127.0.0.1:%d -smtp-bind-addr 127.0.0.1:%d -storage maildir -maildir-path "%s"`

should probably be something like (untested):

`--listen 127.0.0.1:%d --smtp 127.0.0.1:%d --db-file "%s/mailpit.db"`

The command line flags are documented in the [wiki](https://github.com/axllent/mailpit/wiki/Runtime-options) if you need more information.

**Comment by N6REJ** [comment]
They have the ability to change ports if they desire.
i'm thinking here they only have the option for listen and smtp?
This is the old method here...
```
    protected function replaceAll($params) {
        $content = file_get_contents($this->bearsamppConf);

        foreach ($params as $key => $value) {
            $content = preg_replace('|' . $key . ' = .*|', $key . ' = ' . '"' . $value.'"', $content);
            $this->bearsamppConfRaw[$key] = $value;
            switch ($key) {
                case self::LOCAL_CFG_API_PORT:
                    $this->apiPort = intval($value);
                    break;
                case self::LOCAL_CFG_UI_PORT:
                    $this->uiPort = intval($value);
                    break;
                case self::LOCAL_CFG_SMTP_PORT:
                    $this->smtpPort = intval($value);
                    break;
            }
        }

        file_put_contents($this->bearsamppConf, $content);
    }
 ```

**Comment by N6REJ** [comment]
Also, do you have a logo?  just an fyi, we will be ... advertising?.... stating anyway, that we use mailpit so hopefully will gain you some users

**Comment by N6REJ** [comment]
still doing something wrong.
![image](https://user-images.githubusercontent.com/1850089/191186873-103c3885-4493-431b-a221-298876c3b968.png)

**Comment by N6REJ** [comment]
I checked the error log and we get 
```
Error: unknown command "E:/Development/MY_PROJECTS/bearsampp-development/Bearsampp/bin/tmp/release/Bearsampp-lite-2022.09.01/tmp/mailpit/mailpit.db" for "mailpit"
Run 'mailpit --help' for usage.
```

**Comment by axllent** [comment]
It looks to me as if incomplete flags / arguments are being passed to Mailpit, however I don't know Bearsampp at all so you really should be asking one of their team how to do it. The only direction I can give you is to try Mailpit on the commandline to get the correct flags and arguments, and then modify the PHP script accordingly. Mailpit should be working as expected on Windows as I've tested this myself.

Is there a way to print out the "final command" (as in what the PHP script is actually trying to run)?

**Comment by N6REJ** [comment]
We are the team thats developing it.  Ergo our struggles.
when we do a --help this is what we see
![image](https://user-images.githubusercontent.com/1850089/191255063-a7ffc168-0022-4ee7-bb02-34e42c52561b.png)

I'll have to see if there is a way to actually dump the output.

**Comment by axllent** [comment]
Ahh, that makes more sense to me now. The help you are getting is for the built in sendmail functionality, this means that the Mailpit command your are running isn't executing the binary directly, but rather a link to the binary.

When run, Mailpit detects if the command is executing a symlink, and if so switches to sendmail. This allows a developer to easily substitute the systems sendmail binary with just a symlink.

Can you please tell me what happens when your script runs prior to executing? Does it extract Mailpit and then link to it first? If so, can you provide me more information on what that link is called, etc?

**Comment by axllent** [comment]
Actually I'm starting to wonder if for instance you're running it as just "mailpit" in your script (the windows binary is called "mailpit.exe"), or potentially "Mailpit.exe" etc. If the command run does not exactly match (1:1) the binary name then it invoked sendmail.

I should probably relax the rules on the name matching (specifically for Windows as it doesn't distinguish letter casing, and the command can ignore .exe in the executable name when the binary is in your $PATH), however it would be very helpful to me to know a few more details from you. If you ran the above command as `mailpit.exe --help` you should get a different help screen.

**Comment by N6REJ** [comment]
yes, its totally different.  
![image](https://user-images.githubusercontent.com/1850089/191402995-cdf19082-e42c-4e37-9c25-29f1e80f0fac.png)

I'll look over the code tonight and see what I can dig up.  The main problem right now is nssm or winbinder is not actually creating it as a service.

**Comment by axllent** [comment]
That explains it, thanks - your script is currently invoking it as "mailpit" whereas the actual executable file is "mailpit.exe", so Mailpit is automatically assuming it's a symlink, so it's invoking the sendmail functionality.

I will push an update in a few hours that should fix that for Windows, and which hopefully gets you a step further to integrating Mailpit in your software. I'd say that the reason it's not currently able to set it up as a service is that Mailpit is currently returning an error when you try start it.

**Comment by N6REJ** [comment]
that would be great.. tyvm!  I'm pulling my hair out trying to make heads/tails over why its being a brat LOL.

**Comment by axllent** [comment]
I've released [1.1.7](https://github.com/axllent/mailpit/releases/tag/1.1.7) which hopefully solves your issue - or at least gets you to your next step.

As for your PHP, all references to apiPort can be removed (there is no API port configuration fro Mailpit, in fact it doesn't have an API like MailHog does). There is however [one section](https://github.com/Bearsampp/Bearsampp/blob/mailpit/core/classes/bins/class.bin.mailpit.php#L125-L130) that references the apiPort, which may or may not be substitution, so tread lightly.

**Comment by N6REJ** [comment]
I think we're getting closer... 
When I check the log after it says it can't start the service I see...
```
[2022-09-21 01:48:31] E_NOTICE Undefined index: mailpitUiPort in /core/classes/bins/class.bin.mailpit.php on line 44
  #1  Binmailpit->reload(mailpit, bins) called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\bins\class.bin.mailpit.php:26]
  #2  Binmailpit->__construct(mailpit, bins) called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\bins\class.bins.php:56]
  #3  Bins->getmailpit() called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\bins\class.bins.php:136]
  #4  Bins->getServices() called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\actions\class.action.startup.php:30]
  #5  ActionStartup->__construct(Array ()) called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\actions\class.action.php:65]
  #6  Action->process() called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\bootstrap.php:19]

[2022-09-21 01:48:31] # Bearsampp 2022.09.01 # ERROR: Invalid parameter 'mailpitUiPort' : 0
[2022-09-21 01:48:41] E_NOTICE Undefined index: mailpitUiPort in /core/classes/bins/class.bin.mailpit.php on line 44
  #1  Binmailpit->reload() called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\bins\class.bin.mailpit.php:247]
  #2  Binmailpit->setVersion(1.1.7) called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\bins\class.bin.mailpit.php:238]
  #3  Binmailpit->updateConfig(, 0, ) called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\class.module.php:107]
  #4  Module->update() called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\bins\class.bins.php:34]
  #5  Bins->update() called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\actions\class.action.startup.php:497]
  #6  ActionStartup->updateConfig() called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\actions\class.action.startup.php:119]
  #7  ActionStartup->processWindow(82452472, 1002, 82452472, 0, 0)
```

Which is in here. https://github.com/Bearsampp/Bearsampp/blob/da154a05c6f6808e765bb175f369144d61315aad/core/classes/bins/class.bin.mailpit.php#L29-L46

Just as an fyi.  When the program "loads" it creates a "current" folder which is an exact copy of the current version that supposed to be running.  This is due to us supporting multiple version of programs.
php is a good example.  They might want php8.0 one moment and php 8.1.9 the next.  So when they change versions, it calls a reload function that replaces "current" with the new version if that makes sense.
so, the mailpit that will be loaded/executed will live here
![image](https://user-images.githubusercontent.com/1850089/191435198-cba85bfd-662c-44a1-8680-83784e26e0a0.png)

**Comment by axllent** [comment]
@N6REJ I really don't think I can help you here, as the issue appears to be related to your scripts. From what I can see (in your message), I think the line `Bearsampp 2022.09.01 # ERROR: Invalid parameter 'mailpitUiPort' : 0` (which is coming from [here](https://github.com/Bearsampp/Bearsampp/blob/da154a05c6f6808e765bb175f369144d61315aad/core/classes/bins/class.bin.mailpit.php#L68-L71)) may be the key. I think your scripts are returning an error before it even tries to run the binary. It looks to me like your scripts aren't interpreting your configuration file correctly. 

Again, if it is actually running Mailpit, we need to know what the actual command is (that it is executing).

**Comment by N6REJ** [comment]
the ui was my stupid typo error.  
I do have good news though.. the program no longer locks up when running.
I still get the error
![image](https://user-images.githubusercontent.com/1850089/191442312-c65b86cd-074c-47b8-812a-02807dd8156a.png)
I don't think its actually running mailpit yet.
The only error I'm seeing ( after starting dev mode log reporting ) is 
```
  #5  WinBinder->messageBox(mailpit 1.1.7 (bearsamppmailpit) service cannot be installed :
- Cannot start the service : Status 7 (7 : The service is paused.), 16, Startup error) called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\class.winbinder.php:435]
  #6  WinBinder->messageBoxError(mailpit 1.1.7 (bearsamppmailpit) service cannot be installed :
- Cannot start the service : Status 7 (7 : The service is paused.), Startup error) called at [E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\core\classes\actions\class.action.startup.php:149]
  #7  ActionStartup->processWindow(80985256, 1002, 80985256, 0, 0)
  ```
  
>. I think your scripts are returning an error before it even tries to run the binary.
I think your 100% correct.
you've gotten me a LOT closer.  I'll let you know either way what happens.
The one bright spot is if I click on "mailpit" in the menu it goes to "http://localhost:8025" which is what it should do afaik.

**Comment by N6REJ** [comment]
The one spot that perhaps you can help with.. is the ajax routine.
https://github.com/Bearsampp/Bearsampp/blob/mailpit/core/resources/homepage/ajax/ajax.mailpit.php
with mailhog it worked in 7.4.30 but NOT 8.x+
right this minute it breaks all ajax functions in the dashboard.
I don't know if its related to the service issues.

**Comment by N6REJ** [comment]
@axllent I think I found what you've been asking for.
```
[2022-09-21 02:48:58] # Bearsampp 2022.09.01 # DEBUG: Create service
[2022-09-21 02:48:58] # Bearsampp 2022.09.01 # DEBUG: -> service: bearsamppmailpit
[2022-09-21 02:48:58] # Bearsampp 2022.09.01 # DEBUG: -> display: Bearsampp mailpit
[2022-09-21 02:48:58] # Bearsampp 2022.09.01 # DEBUG: -> description: Bearsampp mailpit
[2022-09-21 02:48:58] # Bearsampp 2022.09.01 # DEBUG: -> path: E:\Development\MY_PROJECTS\bearsampp-development\Bearsampp\bin\tmp\release\Bearsampp-lite-2022.09.01\bin\mailpit\current\mailpit.exe
[2022-09-21 02:48:58] # Bearsampp 2022.09.01 # DEBUG: -> params: --listen 127.0.0.1:8025 --smtp 127.0.0.1:1025 --db-file "E:/Development/MY_PROJECTS/bearsampp-development/Bearsampp/bin/tmp/release/Bearsampp-lite-2022.09.01/tmp/mailpit/mailpit.db"
[2022-09-21 02:48:58] # Bearsampp 2022.09.01 # DEBUG: -> stdout: E:/Development/MY_PROJECTS/bearsampp-development/Bearsampp/bin/tmp/release/Bearsampp-lite-2022.09.01/logs/mailpit.out.log
[2022-09-21 02:48:58] # Bearsampp 2022.09.01 # DEBUG: -> stderr: E:/Development/MY_PROJECTS/bearsampp-development/Bearsampp/bin/tmp/release/Bearsampp-lite-2022.09.01/logs/mailpit.err.log
```
this was in the nssm.log which I couldn't see before I turned on dev logging.

**Comment by axllent** [comment]
The short answer is I don't know. It looks OK to me (the flags & args being passed to it), but you're asking me to debug **your** application, but I have no idea at all how your application actually works. This includes the SMTP check (ajax script) - I can only assume it checks a TCP port if its open, but I have no way of telling if that checking functionality works, so I can't tell, sorry. I also do not know what "the service is paused" means - what is paused exactly? Mailpit doesn't pause, so either it's something in your application that is paused, or the error reported by your application is wrong. I really don't mean to sound rude, but I don't see how I can help you without learning how your entire system works (which I don't have time or energy to do unfortunately).

http://localhost:8025/ should work if Mailpit is running (assuming Mailpit is running on the host and not in a docker container or similar).

**Comment by N6REJ** [comment]
ok.. ty for your time.  you've been more then gracious.

**Comment by axllent** [comment]
No problem and good luck! If you need Mailpit support then please feel free to submit a new issue :+1:
